# Generated by Django 5.2.5 on 2025-08-26 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=True)),
                ('email', models.EmailField(blank=True, max_length=500, null=True)),
                ('count_views', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('Web Development', 'Web Development'), ('Desktop Development', 'Desktop Development')], default='Web Development')),
            ],
        ),
    ]
